title: "Example Docs Site"
description: "Minimal Just the Docs TOC sidebar example"

remote_theme: pmarsceill/just-the-docs
markdown: kramdown

# enable site-wide nav and per-page TOC
nav: true
has_toc: true

# use GitHub-Flavored Markdown (optional but recommended)
kramdown:
  input: GFM
  math_engine: mathjax

# automatically apply your custom layout to all Markdown pages
defaults:
  - scope:
      path: ""          # all files
      type: "pages"     # or omit type if you want posts too
    values:
      layout: custom
